# .github/workflows/ci.yml
name: Python CI/CD

on:
  push:
    branches:
      - main # Triggers the workflow on pushes to the 'main' branch
      - develop # Add other development branches if you use them
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest # Specifies the operating system for the job (Ubuntu Linux)

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Action to retrieve your repository's code

    - name: Set up Python
      uses: actions/setup-python@v5 # Action to set up a Python environment
      with:
        python-version: '3.10' # Specifies the Python version to use for the job

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip # Ensures pip is up-to-date
        pip install -r requirements.txt # Installs all libraries listed in requirements.txt

    - name: Run tests with pytest
      # These environment variables are securely passed from GitHub Secrets.
      # They are only available during the workflow run and are not exposed in logs.
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        GOOGLE_CSE_ID: ${{ secrets.GOOGLE_CSE_ID }}
        GOOGLE_API_KEY_FOR_SEARCH: ${{ secrets.GOOGLE_API_KEY_FOR_SEARCH }}
      run: |
        pytest # Executes pytest. It will automatically discover and run tests in the 'tests/' directory.